// <auto-generated />
using Excel_Demo_2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Excel_Demo_2.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Excel_Demo_2.Models.PeerGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Empty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryQuartile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Particular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeerGroupAverage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeerGroupMax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeerGroupMedian")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeerGroupMin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("peerGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
